{{/*
Service Account for MnemoCore
*/}}
{{- if .Values.mnemocore.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mnemocore.serviceAccountName" . }}
  labels:
    {{- include "mnemocore.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.mnemocore.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
